[package]
name = "agrega"
description = "High-quality 2D graphics engine based on Anti-grain Geometry"
version = "0.1.1"
edition = "2021"
rust-version = "1.73.0"
authors = [
	"Maxim Shemanarev (McSeem)",
	"Brian Savage <savage13@gmail.com>",
	"jarris2268",
	"José Luis Cruz <joseluis@andamira.net>",
]
repository = "https://github.com/andamira/agrega"
license = "BSD-2-Clause"
include = [
	"/src/**/*.rs",
	"/Cargo.toml",
	"/LICENSE*",
	"/README.md",
	"/images",
]
categories = ["rendering::graphics-api", "no-std"]
keywords = ["2d", "graphics"]
publish = true

[features]
# for now, almost everything depends on alloc
default = ["alloc"]

std = ["alloc"]
alloc = []
no_std = ["devela/libm"]
safe = []
unsafe = []
nightly = []

text = ["std", "freetype-rs"]
docsrs = ["nightly", "std", "freetype-rs"]


[dependencies]
devela = { version = "0.18", features = ["ops"] }

freetype-rs = { version = "0.32.0", optional = true }
# font-loader = "0.11.0"

[dependencies.image]
version = "0.24.7"
default-features = false
features = ["png", "gif", "pnm", "bmp", "jpeg"]

[package.metadata.docs.rs]
no-default-features = true
features = ["docsrs"]
